apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # Base64 encoded "rootpassword"
  DB_USER: bXl1c2Vy  # Base64 encoded "myuser"
  DB_PASSWORD: bXlwYXNzd29yZA==  # Base64 encoded "mypassword"
